# sql script to create the console table
CREATE TABLE searchresult (
                              id INT AUTO_INCREMENT PRIMARY KEY,
                              title VARCHAR(255) NOT NULL,
                              snippet TEXT,
                              url VARCHAR(255) NOT NULL
);
INSERT INTO searchresult (title, snippet, url) VALUES
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2B%2B'),
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2B%2B'),
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2B%2B'),
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2B%2B'),
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAS, cript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2B%2B'),
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2B%2B'),
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2B%2B'),
                                                   ('Java Programming', 'Java is a high-level, class-based, object-oriented programming language.', 'https://en.wikipedia.org/wiki/Java_(programming_language)'),
                                                   ('Python Programming', 'Python is an interpreted, high-level and general-purpose programming language.', 'https://en.wikipedia.org/wiki/Python_(programming_language)'),
                                                   ('JavaScript Programming', 'JavaScript, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification.', 'https://en.wikipedia.org/wiki/JavaScript'),
                                                   ('C++ Programming', 'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.', 'https://en.wikipedia.org/wiki/C%2'),
                                                   ('Ruby Programming', 'Ruby is an interpreted, high-level, general-purpose programming language.', 'https://en.wikipedia.org/wiki/Ruby_(programming_language');